function c = class_transformFuncHandles(funcType, addBias, ...
   func_signal, func_output_effDeriv, ...   
   func_costOverSignalGrad_thruCostOverOutputGrad, ...
   func_costOverInputGrad_thruCostOverSignalGrad, ...
   func_costOverWeightGrad_thruCostOverSignalGrad)

   c.funcType = funcType;
   c.addBias = addBias;
   c.func_signal = func_signal;
   c.func_output_effDeriv = func_output_effDeriv;
   c.func_costOverSignalGrad_thruCostOverOutputGrad = ...
      func_costOverSignalGrad_thruCostOverOutputGrad;
   c.func_costOverInputGrad_thruCostOverSignalGrad = ...
      func_costOverInputGrad_thruCostOverSignalGrad;
   c.func_costOverWeightGrad_thruCostOverSignalGrad = ...
      func_costOverWeightGrad_thruCostOverSignalGrad;
      
   c = class(c, 'class_transformFuncHandles');
   
endfunction