function f = defineTransformFunc_input_n_param...
   (funcType, addBias, ...
   funcSignalVal, funcOutputVal, ...
   funcOutputOverSignalDeriv_genForm, ...
   funcOutputOverSignalDeriv_effForm, ...
   funcSignalOverInputDeriv, ...
   funcSignalOverParamDeriv, ...
   funcOutputOverInputDeriv, ...
   funcOutputOverParamDeriv, ...
   funcCostOverSignalGrad_thruCostOverOutputGrad, ...
   funcCostOverInputGrad_thruCostOverOutputGrad, ...
   funcCostOverParamGrad_thruCostOverOutputGrad, ...
   funcParamRegulCostAvg, ...
   funcParamRegulCostAvgGrad)

   f.funcType = funcType;   
   f.addBias = addBias;   
   f.funcSignalVal = funcSignalVal;   
   f.funcOutputVal = funcOutputVal;   
   f.funcOutputOverSignalDeriv_genForm = ...
      funcOutputOverSignalDeriv_genForm;   
   f.funcOutputOverSignalDeriv_effForm = ...
      funcOutputOverSignalDeriv_effForm;   
   f.funcSignalOverInputDeriv = ...
      funcSignalOverInputDeriv;      
   f.funcSignalOverParamDeriv = ...
      funcSignalOverParamDeriv;      
   f.funcOutputOverInputDeriv = ...
      funcOutputOverInputDeriv;      
   f.funcOutputOverParamDeriv = ...
      funcOutputOverParamDeriv;   
   f.funcCostOverSignalGrad_thruCostOverOutputGrad = ...
      funcCostOverSignalGrad_thruCostOverOutputGrad;      
   f.funcCostOverInputGrad_thruCostOverOutputGrad = ...
      funcCostOverInputGrad_thruCostOverOutputGrad;      
   f.funcCostOverParamGrad_thruCostOverOutputGrad = ...
      funcCostOverParamGrad_thruCostOverOutputGrad;   
   f.funcParamRegulCostAvg = ...
      funcParamRegulCostAvg;
   f.funcParamRegulCostAvgGrad = ...
      funcParamRegulCostAvgGrad;
   
end