function f = ...
   embedClassIndcs_inRealFeats_rowMat...
   (classIndcs_Mat_casesInRows, ...
   realFeats_Mat_classesInRows)
  
   f.val = reshape(realFeats_Mat_classesInRows...
      (classIndcs_Mat_casesInRows'(:), :)', ...
      columns(classIndcs_Mat_casesInRows) ...
      * columns(realFeats_Mat_classesInRows), [])';
   
   f.costOverRealFeatsGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad) ...
   embedClassIndcs_inRealFeats_rowMat_costOverRealFeatsGrad...
      (costOverOutputGrad, ...
      classIndcs_Mat_casesInRows, ...
      realFeats_Mat_classesInRows);

end