function f = ...
   embedClassIndcs_inRealFeats_rowMat_costOverRealFeatsGrad...
      (costOverOutputGrad, ...
      classIndcs_Mat_casesInRows, ...
      realFeats_Mat_classesInRows)
      
   [nC nF] = size(realFeats_Mat_classesInRows);      
   f = zeros([nC nF]);
   expansionMat = eye(nC);
   for (j = 1 : columns(classIndcs_Mat_casesInRows))
      f += expansionMat(:, classIndcs_Mat_casesInRows(:, j)) ...
         * costOverOutputGrad(:, ((j - 1) * nF + 1) : (j * nF));
   endfor
      
end