function f = funcEmbedClassIndcs_inRealFeats_rowMat

   funcType = 'Embed Class Indices in Real Features';
   
   addBias = false;
   
   funcSignalVal = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      embedClassIndcs_inRealFeats_rowMat...
      (classIndcs_rowMat, realFeats_rowMat).val;
  
   funcOutputVal = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      funcSignalVal...
      (classIndcs_rowMat, realFeats_rowMat);

   funcOutputOverSignalDeriv_genForm = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      linearFunc_Mat(funcSignalVal...
      (classIndcs_rowMat, realFeats_rowMat));
      
   funcOutputOverSignalDeriv_effForm = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      1;   

   funcSignalOverInputDeriv = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      []; % discreet input, not differientiable
      
   funcSignalOverParamDeriv = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      []; % cumbersome to define, not needed
      
   funcOutputOverInputDeriv = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      funcSignalOverInputDeriv...
      (classIndcs_rowMat, realFeats_rowMat);

   funcOutputOverParamDeriv = ...
      @(classIndcs_rowMat, realFeats_rowMat) ...
      funcSignalOverParamDeriv...
      (classIndcs_rowMat, realFeats_rowMat);
      
   funcCostOverSignalGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad, ...
      classIndcs_rowMat, realFeats_rowMat) ...
      costOverOutputGrad;
      
   funcCostOverInputGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad, ...
      classIndcs_rowMat, realFeats_rowMat) ...
      []; % discreet input, not differientiable

   funcCostOverParamGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad, ...
      classIndcs_rowMat, realFeats_rowMat) ...
      embedClassIndcs_inRealFeats_rowMat...
      (classIndcs_rowMat, ...
realFeats_rowMat).costOverRealFeatsGrad_thruCostOverOutputGrad...
      (costOverOutputGrad);
    
   f = defineTransformFunc_input_n_param...
      (funcType, addBias, ...
      funcSignalVal, funcOutputVal, ...
      funcOutputOverSignalDeriv_genForm, ...
      funcOutputOverSignalDeriv_effForm, ...
      funcSignalOverInputDeriv, ...
      funcSignalOverParamDeriv, ...
      funcOutputOverInputDeriv, ...
      funcOutputOverParamDeriv, ...
      funcCostOverSignalGrad_thruCostOverOutputGrad, ...
      funcCostOverInputGrad_thruCostOverOutputGrad, ...
      funcCostOverParamGrad_thruCostOverOutputGrad);

end