function [costAvg accuracyAvg] = costAvg_exclWeightPenalty...
   (ffNN, input_batches, targetOutputs_batches, ...
   targetOutputs_areClassIndcsColVecs_ofNumClasses = false, ...
   batchDim = 3)
   
   numBatches = max(size(input_batches, batchDim), ...
      size(targetOutputs_batches, batchDim));
   
   if (numBatches == 1)     
      [~, costAvg, ~, ~, accuracyAvg] = fProp_bProp(ffNN, ...
         input_batches, targetOutputs_batches, ...
         targetOutputs_areClassIndcsColVecs_ofNumClasses, ...
         {{'L2'} [0]}, false);         
   else      
      costAvg = accuracyAvg = 0;
      for (b = 1 : numBatches)      
         input_batch = arrSubsetHighestDim(input_batches, b);
         targetOutputs_batch = ...
            arrSubsetHighestDim(targetOutputs_batches, b);
         [~, c, ~, ~, a] = fProp_bProp(ffNN, input_batch, ...
            targetOutputs_batch, ...
            targetOutputs_areClassIndcsColVecs_ofNumClasses, ...
            {{'L2'} [0]}, false);
         costAvg += (c - costAvg) / b;
         accuracyAvg += (a - accuracyAvg) / b;
      endfor      
   endif
   
endfunction