---
title: 'Neural Networks for Pattern Recognition: Agenda'
output: pdf_document
fontsize: 12pt
geometry: margin=0.9cm
---



### SESSION 1

1. Overview of Supervised Machine Learning; Training & Test Data Sets
2. EXAMPLE: Linear Regression; Squared-Error Cost Function, Root Mean Square Error (RMSE)
3. Regularization by Weight Penalty; Its Effects on Training & Test Performances
4. Validation Data Set; Learning Curves; Weight Regularization by Early Stopping
5. EXAMPLE: Logistic Regression; Cross-Entropy Cost Function

HOMEWORK:

1. Regularizing Logistic Regression by Weight Penalty
2. Regularizing Logistic Regression by Early Stopping



### SESSION 2

1. Neural Networks with Logistic/Tanh Transformation Functions
2. EXAMPLE: Learning Logical Functions AND & OR
3. EXAMPLE: Learning Complicated, Many-Variable AND & OR Logical Combinations
4. EXAMPLE: Learning Hand-Written Digits; Hidden Layer Nodes as Feature Detectors
5. How Neural Networks Learn: Forward Propagation & Backward Propagation
6. Softmax Transformation Function for Multi-Class Classification; Comparison with Collection of One-vs.-All Binary Classifiers


HOMEWORK:

1. CASE STUDY: Google Self-Driving Car; Video on Early Self-Driving Car



### SESSION 3

1. CASE STUDY DISCUSSION: Google Self-Driving Car
2. EXAMPLE: Learning Poker Hands; Challenges Posed by Skewed Classes; Mini-Batch Learning
3. FINAL EXAM (Live Team Competition): Human Activity Tracking Dataset for Classifying Quality of Bicep Curls