---
title: 'youTeach.machineLearn Package: Installation Guide'
output: pdf_document
fontsize: 12pt
geometry: margin=0.9cm
---

<br><br>



### 1. GitHub

Sign up for a GitHub account at http://github.com if you are not currently a user.

Download the GitHub desktop app at http://windows.github.com (Windows) or http://mac.github.com (Mac). Sign in with your online account credentials.

<br>



### 2. Fork & Clone *youTeach.machineLearn* GitHub Repository

Go to the ***youTeach.machineLearn*** code repository at this link: http://github.com/MBALearnsToCode/youTeach.machineLearn.

At the top-right area of the browser screen, find and press the "Fork" button to obtain a copy of the repo.

Go to your GitHub desktop app. At the top-left corner of the app screen, find a "+" sign. Click that "+" sign, and in the resulting drop-down menu toggle to "Clone". Select the ***youTeach.machineLearn*** repo, specify a folder on your local disk drive, and clone the online repo to your local drive. This may take a short while because besides code, the repo also contains lots of academic reference materials.

<br>



### 3. Octave

Octave is a free programming language compatible with Matlab.

You can download the latest version 3.8 with a graphical user interface from this link: http://mxeoctave.osuv.de/octave-3.8.2-3-installer.exe. This version is actually not yet official, but it seems stable already.

Run the file to install Octave. The default options should be good. If prompted to install Java first, do so before installing Octave.

<br>



### 4. Start up *youTeach.machineLearn* package every time wanting to use it in Octave

In Octave, whenever you want to use the ***youTeach.machineLearn*** package: go to Octave's file browser, navigate to the ***youTeach.machineLearn*** folder on your local drive, and check that there is a file named "start.m" there. In Octave's command window, type "start" and press Enter.

The package will then be added to Octave's search path, i.e. the package's functions will become ready to use.
 