function f = ffNN_plotLearningCurves...
   (trainCostAvg_exclWeightPenalty_currChunk, ...
   trainAccuracyAvg_text, ...
   trainCostsAvg_exclWeightPenalty_approx, ...   
   validCostAvg_exclWeightPenalty, validAccuracyAvg_text, ...
   validCostsAvg_exclWeightPenalty_0asNA, ...  
   chunkNum, trainCostApproxChunk_numBatches, batchSize, ...
   trainElapsedTime_numMins)

   clf;
   hold on;
   title('LEARNING CURVES (Forward-Feeding Neural Network)');
xlabel(sprintf('%i CHUNKS (1 Chunk = %i Batches, 1 Batch = %i Cases) | elapsed: %.3gm', ...
      chunkNum, trainCostApproxChunk_numBatches, batchSize, ...
      trainElapsedTime_numMins));
   ylabel('Avg COST (excl Weight Penalty)');
   plot(trainCostsAvg_exclWeightPenalty_approx, 'b');
   plot(validCostsAvg_exclWeightPenalty_0asNA, ...
      '.', 'color', 'r', 'markersize', 9);
   legend(sprintf('TRAINING (last chunk) = %.3g%s', ...          
      trainCostAvg_exclWeightPenalty_currChunk, ...
      trainAccuracyAvg_text), ...
      sprintf('VALIDATION = %.3g%s', ...
      validCostAvg_exclWeightPenalty, ...
      validAccuracyAvg_text));
   hold off;
   pause(0);

endfunction