function ffNN_overview(ffNN)
   
   ffNN_0 = ffNN;   
   ffNN_0.hypoOutput = ...
      printArrDimSizes(ffNN_0.hypoOutput);
   ffNN_0.inputDimSizes_perCase = ...
      mat2str(ffNN_0.inputDimSizes_perCase);
   ffNN_0.paramDimSizes = ...
      '(see Parameters below)';
   transformFuncs = cellfun(@(transformFunc) ...
      strcat(upper(transformFunc.funcType), ' with' , ...
      sprintf(' %i', transformFunc.addBias), ' bias'), ...
      ffNN_0.transformFuncs(2 : end), 'UniformOutput', false);
   ffNN_0.transformFuncs = ['' transformFuncs];
   ffNN_0.params = ...
      printArrDimSizes_chain(ffNN_0.params);
   ffNN_0.paramGrads = ...
      '(same sizes as Parameters)';
   ffNN_0.signalGrads = ...
      printArrDimSizes_chain(ffNN_0.signalGrads);
   ffNN_0.activs = ...
      printArrDimSizes_chain(ffNN_0.activs);
   ffNN_0.activGrads = ...
      '(same sizes as Activities)';
   ffNN_0.regulParams = printArrDimSizes(ffNN_0.regulParams);
   ffNN_0

end