function [costAvg_wRegul inputGrad_n_paramGrads_colVec] = ...
   ffNN_costWRegul_n_inputGrad_n_paramGrads...
   (input_n_params_colVec, ffNN, targetOutput, ...
   regulParam = 0, returnInputGrad = true)
   
   NN = ffNN;
   numInputElems = length(input_n_params_colVec) ...
      - NN.numParams;   
   inputDimSizes_perCase = NN.inputDimSizes_perCase;   
   inputDimSizes = ...
      [(numInputElems / prod(inputDimSizes_perCase)) ...
      inputDimSizes_perCase];
   input_n_params = convertColVecToArrs...
      (input_n_params_colVec, ...
      [inputDimSizes NN.paramDimSizes]);
   input_rowMat = input_n_params{1};
   NN.params = input_n_params(2 : end);

   NN = ffNN_fProp_bProp...
      (input_rowMat, NN, targetOutput, regulParam);

   costAvg_wRegul = NN.costAvg_wRegul;

   if (returnInputGrad)
      inputGrad_n_paramGrads_colVec = ...
         convertArrsToColVec...
         ([NN.activGrads{1} NN.paramGrads]);
   else
      inputGrad_n_paramGrads_colVec = ...
         convertArrsToColVec(NN.paramGrads);
   endif

end