function f = ffNN_costAvg_noRegul(ffNN, input_batches, ...
   targetOutput_batches, ...
   targetOutput_isClassIndcsColVec_ofNumClasses, ...
   batchDim = 3)
   
   numBatches = min(size(input_batches, batchDim), ...
      size(targetOutput_batches, batchDim));
   
   if (numBatches == 1)   
     
      f = ffNN_fProp_bProp(ffNN, input_batches, ...
         targetOutput_batches, ...
         targetOutput_isClassIndcsColVec_ofNumClasses, ...
         {'L2' []}, false).costAvg_noRegul;
         
   else
      
      f = 0;
      
      for (b = 1 : numBatches)      
         input_batch = arrSubsetHighestDim(input_batches, b);
         targetOutput_batch = ...
            arrSubsetHighestDim(targetOutput_batches, b);
         f += (ffNN_fProp_bProp(ffNN, input_batch, ...
            targetOutput_batch, ...
            targetOutput_isClassIndcsColVec_ofNumClasses, ...
            {'L2' []}, false).costAvg_noRegul ...
            - f) / b;   
      endfor
      
   endif
   
end