function f = accuracyAvg_logistic(hypoArr, targetArr, ...
   posSkewnesses = [1])
   
   negSkewnesses = 2 - posSkewnesses;
   
   denominator = ...
      (1 ./ posSkewnesses + 1 ./ negSkewnesses) / 2;
      
   f = arrSumAllDims(bsxfun(@rdivide, ...
      bsxfun(@rdivide, ...
      targetArr .* hypoArr, posSkewnesses) ...
      + bsxfun(@rdivide, (1 - targetArr) .* (1 - hypoArr), ...
      negSkewnesses), denominator)) / numel(targetArr);

endfunction