function f = costOverSignalGrad...
   (hypoOutput_rowMat, targetOutput_rowMat, ...
   costFuncType = 'CE-L', classSkewnesses = [1])
   
   [m n] = size(targetOutput_rowMat);
   
   for (j = (length(classSkewnesses) + 1) : n)
      classSkewnesses(j) = classSkewnesses(j - 1);
   endfor
   if strcmp(costFuncType, 'CE-S')      
      classSkewnesses /= (sum(classSkewnesses) / n);      
   endif   
   
   switch (costFuncType)
   
      case ('SE')
         f = (hypoOutput_rowMat - targetOutput_rowMat) / m;
         
      case ('CE-L')
         posSkewnesses = classSkewnesses;
         negSkewnesses = 2 - posSkewnesses;
         balancedClasses = ...
            equalTest(posSkewnesses, negSkewnesses);
         if (balancedClasses)
            f = (hypoOutput_rowMat - targetOutput_rowMat) / m;
         else
            f = (bsxfun(@rdivide, ...
               targetOutput_rowMat .* (hypoOutput_rowMat - 1), ...
               posSkewnesses) ...
               + bsxfun(@rdivide, ...
               (1 - targetOutput_rowMat) .* hypoOutput_rowMat, ...
               negSkewnesses)) / m;
         endif
      
      case ('CE-S')
         balancedClasses = equalTest...
            (max(classSkewnesses), min(classSkewnesses));
         if (balancedClasses)
            f = (hypoOutput_rowMat - targetOutput_rowMat) / m;
         else
            hypoOutput_rep = ...
               arrRepAcrossNewDims...
               (hypoOutput_rowMat, 2, n); 
            targetOutput_rep = ...
               permute(arrRepAcrossNewDims...
               (targetOutput_rowMat, 2, n), [1 3 2]);
            iMat_rep = permute(arrRepAcrossNewDims...
               (eye(n), 2, m), [3 1 2]);
            classSkewnesses_rep = permute(arrRepAcrossNewDims...
               (repmat(classSkewnesses, [m 1]), 2, n), [1 3 2]);
            f = arrSumAcrossDims...                        
               ((targetOutput_rep ...
               .* (hypoOutput_rep - iMat_rep)) ...
               ./ classSkewnesses_rep, 3) / m;
         endif
         
   endswitch
   
endfunction