function f = funcLinear_inputRowMat_n_biasWeightMat...
   (addBias = true)

   funcType = 'linear';
   
   funcSignalVal = ...
      @(input_rowMat, biasWeight_Mat) ...
      addBiasElems(input_rowMat, addBias) ...
      * biasWeight_Mat;
   
   funcOutput_genDeriv = ...
      @(signalVal) ...
      linearFunc_Mat(signalVal, true, 'gen');
      
   funcOutput_effDeriv = ...
      @(signalVal) ...
      linearFunc_Mat(signalVal);
   
   funcOutputVal = ...
      @(input_rowMat, biasWeight_Mat) ...
      funcSignalVal...
      (input_rowMat, biasWeight_Mat);

   funcOutputOverSignalDeriv_genForm = ...
      @(input_rowMat, biasWeight_Mat) ...
      funcOutput_genDeriv(funcSignalVal...
      (input_rowMat, biasWeight_Mat)).deriv;
      
   funcOutputOverSignalDeriv_effForm = ...
      @(input_rowMat, biasWeight_Mat) ...
      funcOutput_effDeriv(funcSignalVal...
      (input_rowMat, biasWeight_Mat)).deriv;
   
   funcSignalOverInputDeriv = ...
      @(input_rowMat, biasWeight_Mat) ...
      linearOutputOverInputDeriv_rowMat...
      (rows(input_rowMat), ...
      rmBiasElems(biasWeight_Mat, addBias));
      
   funcSignalOverBiasWeightDeriv = ...
      @(input_rowMat, biasWeight_Mat) ...
      linearOutputOverWeightDeriv_rowMat...
      (columns(biasWeight_Mat), ...
      addBiasElems(input_rowMat, addBias));
      
   funcOutputOverInputDeriv = ...
      @(input_rowMat, biasWeight_Mat) ...
      funcSignalOverInputDeriv...
      (input_rowMat, biasWeight_Mat);

   funcOutputOverBiasWeightDeriv = ...
      @(input_rowMat, biasWeight_Mat) ...
      funcSignalOverBiasWeightDeriv...
      (input_rowMat, biasWeight_Mat);

   funcCostOverSignalGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad, ...
      input_rowMat, biasWeight_Mat) ...
      costOverOutputGrad;
      
   funcCostOverInputGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad, ...
      input_rowMat, biasWeight_Mat) ...
      costOverOutputGrad ...
      * rmBiasElems(biasWeight_Mat, addBias)';

   funcCostOverBiasWeightGrad_thruCostOverOutputGrad = ...
      @(costOverOutputGrad, ...
      input_rowMat, biasWeight_Mat) ...
      addBiasElems(input_rowMat, addBias)' ...
      * costOverOutputGrad;
   
   f = defineTransformFunc_input_n_param...
      (funcType, addBias, ...
      funcSignalVal, funcOutputVal, ...
      funcOutputOverSignalDeriv_genForm, ...
      funcOutputOverSignalDeriv_effForm, ...
      funcSignalOverInputDeriv, ...
      funcSignalOverBiasWeightDeriv, ...
      funcOutputOverInputDeriv, ...
      funcOutputOverBiasWeightDeriv, ...
      funcCostOverSignalGrad_thruCostOverOutputGrad, ...
      funcCostOverInputGrad_thruCostOverOutputGrad, ...
      funcCostOverBiasWeightGrad_thruCostOverOutputGrad);
      
end