function ffNN_multiLinReg_housePrices...
   (learningRate = 0.3, numIters = 100)

   % load House Prices data
   data = load('housePrices.txt');
   x1 = houseAreas_sqft = data(:, 1);
   x2 = houseNumsBedrooms = data(:, 2);
   X = [x1 x2];
   y = housePrices = data(:, 3);
   m = rows(data);
   
   % Print out some data points
   fprintf('\nFirst 10 examples from the House Prices dataset: \n');
   fprintf('   area = %.0f, numBeds = %.0f, price = %.0f\n', ...
      [x1(1 : 10, :) x2(1 : 10, :) y(1 : 10, :)]');
   
   % Linear regression coefficients - analytic solution
   coeffs_analytic = linRegWeights_analytic(y, X);
   
   % Normalize scales of features for better convergence
   [X_norm mu sigma] = normalizeSubtractDivide(X);
   fprintf('\nLinear Regression Coefficients (analytic solution on normalized features):\n');   
   coeffs_analyticNormalized = linRegWeights_analytic(y, X_norm)
   
   %% Forward-Feeding Neural Net
   %% --------------------------   
   ffNN = class_ffNN...
      (inputDimSizes_perCase_vec = 2, ...
      addlLayersNumsNodes_vec = [], ...
      transformFuncs_list = {'linear'}, ...
      displayOverview = false, ...
      initWeights_rand = false);
   ffNN.normalizeSubtract = mu;
   ffNN.normalizeDivide = sigma;
   
   ffNN = train_conjGrad...
      (ffNN_init = ffNN, ...
      dataArgs_list = {X y 1.0}, ...
      targetOutputs_areClassIndcsColVecs = false, ...
      numIters_perEpoch = 3, ...
      trainNumEpochs = numIters, ...
      trainBatchSize = false, ...   
      trainRandShuff = false, ...
      trainCostApproxChunk_numBatches = 1, ...
      validCostCalcInterval_numChunks = 1, ...
      weightRegulArgs_list = {{'L2'} [0]}, ...
      connectProbs = [1.0], ...
      bestStop = true);
   
   %ffNN = train_gradDesc...
   %   (ffNN_init = ffNN, ...
   %   dataArgs_list = {X y 1.0}, ...
   %   targetOutputs_areClassIndcsColVecs = false, ...
   %   trainNumEpochs = numIters, ...
   %   trainBatchSize = false, ...   
   %   trainRandShuff = false, ...
   %   trainCostApproxChunk_numBatches = 1, ...
   %   validCostCalcInterval_numChunks = 1, ...
   %   learningRate_init = learningRate, ...
   %   momentumRate_init = 9e-1, ...
   %   nesterovAccGrad = true, ...
   %   weightRegulArgs_list = {{'L2'} [0]}, ...
   %   connectProbs = [1.0], ...
   %   bestStop = true);
      
   weights = ffNN.weights;
   fprintf('Linear Regression Coefficients (neural net solution on normalized features):\n');
   weights_ffNN = weights{1}
   
   relativeDiff = distRel(weights_ffNN, coeffs_analyticNormalized)
   
   testArea = 1000;
   testNumBedrooms = 2;
   fprintf('\nPredicted Price of House with Area = %i, No. of Bedrooms = %i:\n', ...
      testArea, testNumBedrooms);
   fprintf('   from Analytic Solution: %g\n', ...
      [1 testArea testNumBedrooms] * coeffs_analytic);
   fprintf('   from ffNN Solution: %g\n', ...
      predict(ffNN, [testArea testNumBedrooms]));
   
   fprintf('\n');   
   
endfunction