function f = rbm_loadFile(loadFileName)

   f = load(loadFileName).rbm_file;
   
   f.transformFunc_fromHid_toVis = ...
      convertText_toTransformFunc...
      (f.transformFunc_fromHid_toVis);
   f.transformFunc_fromVis_toHid = ...
      convertText_toTransformFunc...
      (f.transformFunc_fromVis_toHid);   

endfunction