function model = zzzTest_Hinton_NNML_ex02...
   (trainNumEpochs = 1, Nesterov = false, MacKay = false, ...
   bestStop = false, trainRandShuff = false)

   startTime = time;   
   
   % HYPERPARAMETERS
   % ---------------
   trainBatchSize = 1e2;
   learningRate = 1e-1;
   momentumRate = 0.9;
   numEmbedNodes = 50;
   numHidNodes = 200;
   initBiasWeightSD = 1e-2;

   % PARAMETERS FOR TRACKING TRAINING PROGRESS
   % -----------------------------------------
   trainCostApproxChunk_everyNumBatches = 1e2;
   validCostCalcInterval_everyNumChunks = 1e1;

   % LOAD DATA
   % ---------
   [trainInput trainTargetOutput ...
      validInput validTargetOutput ...
      testInput testTargetOutput ...
      vocab] = loadData();
   numWords = columns(trainInput);
   vocabSize = length(vocab);
   
   % SET UP NEURAL NET
   % -----------------
   ffNN = ffNN_new(numWords, ...
      {[vocabSize numEmbedNodes] ...
      [(numWords * numEmbedNodes + 1) numHidNodes] ...
      [(numHidNodes + 1) vocabSize]}, ...
      {'embedClassIndices_inRealFeatures' ...
      'logistic' 'softmax'}, {}, true, true, ...
      initBiasWeightSD);   

   % TRAIN NEURAL NET
   % ----------------
   if (MacKay)
      regulArgs_list = {{'L2' 'MacKay_empBayes'} []};
   else
      regulArgs_list = {{'L2'} []};
   endif
   ffNN = ffNN_trainGradDesc(ffNN, ...
      {trainInput trainTargetOutput ...
      validInput validTargetOutput ...
      testInput testTargetOutput}, vocabSize, ...
      trainNumEpochs, trainBatchSize, trainRandShuff, ...
      trainCostApproxChunk_everyNumBatches, ...
      validCostCalcInterval_everyNumChunks, ...
      learningRate, momentumRate, Nesterov, ...
      regulArgs_list, bestStop);
   endTime = time;
   duration = endTime - startTime;
   fprintf(1, 'Training took %.2f seconds\n', duration);

end