function m = goodnessAvg(rbm, hid_rowMat = [], vis_rowMat)

   if isempty(hid_rowMat)
      hid_rowMat = updateLayer(rbm, 'hid', vis_rowMat, false);
   endif
   
   m = trace...
      ((addBiasElems(hid_rowMat, rbm.addBiasHid) ...
      * rbm.weights) ...
      * addBiasElems(vis_rowMat, rbm.addBiasVis)')...
      / rows(hid_rowMat);

endfunction